[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dag-framework"
version = "0.1.0"
dependencies = [
    "pillow",
    "imageio",
    "fastapi",
]

[tool.setuptools.packages.find]
where = ["src"]
